[workspace]
members = [
    "crates/forge",
    "crates/test-collector",
    "crates/cast",]

[workspace.package]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/foundry-rs/starknet-foundry"
license = "Apache-2.0"
license-file = "LICENSE"

[workspace.dependencies]
