name: Test CI with pull_request_target

on:
  pull_request:

jobs:
  test_envs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "This message is from the tomek/2141-pull-request-target branch"
      - run: cat .tool-versions

